import { readFavorites } from "./storage/favorites.js";
import { readWatched } from "./storage/watched.js";
export const defaults = () => ({
  filters: {
    query: "",
    synopsis: "",
    yearMin: null,
    yearMax: null,
    ratingMin: null,
    votesMin: null,
    onlyRated: false,
    genres: [],
    genreMode: "any",
    countries: [],
    countryMode: "any",
    director: "",
    actor: "",
    country: "",
    durationMin: null,
    durationMax: null,
    pressMin: null,
    vod: "all",
    watched: "all",
    pivot: [],
  },
  scoring: {
    weights: {
      rating: 60,
      genre: 25,
      year: 15,
      votes: 0,
      press: 0,
      duration: 0,
      country: 0,
      director: 0,
      actor: 0,
      vod: 0,
    },
    bayesian: true,
    m: 100,
    yearMode: "range",
    yearMin: 1990,
    yearMax: 2010,
    targetYear: 1997,
    falloff: 30,
    genreMode: "mean",
    preferences: {},
    durationTarget: 110,
    durationFalloff: 60,
    country: "",
    director: "",
    actor: "",
  },
  sorting: { field: "score", direction: "desc" },
  view: "table",
  pageSize: 50,
  top: 0,
});
export const state = {
  config: defaults(),
  page: 1,
  selected: new Set(),
  favorites: readFavorites(),
  favoritesOnly: false,
  watched: readWatched(),
  watchedOnly: false,
  summary: null,
};
