import { test, expect } from "@playwright/test";

test("film navigation follows results across pages and closes only on outside clicks", async ({ page }) => {
  await page.goto("/");
  await expect(page.locator("#table-view tbody tr")).toHaveCount(250, { timeout: 15000 });
  const titles = page.locator("#table-view .title-button");
  const first = await titles.first().textContent();
  const second = await titles.nth(1).textContent();
  const lastOnPage = await titles.nth(249).textContent();
  await titles.first().click();
  await expect(page.locator(".detail h3").first()).toHaveText(first);
  await expect(page.locator("#film-previous")).toHaveCount(0);
  await page.keyboard.press("ArrowRight");
  await expect(page.locator(".detail h3").first()).toHaveText(second);
  await page.locator(".detail h3").first().click();
  await expect(page.locator("#modal")).toBeVisible();
  await page.locator(".detail h3").first().evaluate((target) => {
    const touch = (x) => new Touch({ identifier: 1, target, clientX: x, clientY: 200 });
    target.dispatchEvent(new TouchEvent("touchstart", { bubbles: true, touches: [touch(100)] }));
    target.dispatchEvent(new TouchEvent("touchend", { bubbles: true, touches: [], changedTouches: [touch(250)] }));
  });
  await expect(page.locator(".detail h3").first()).toHaveText(first);
  await page.mouse.click(2, 2);
  await expect(page.locator("#modal")).not.toBeVisible();
  await titles.nth(249).click();
  await expect(page.locator(".detail h3").first()).toHaveText(lastOnPage);
  await page.keyboard.press("ArrowRight");
  await expect(page.locator("#film-position")).toContainText("251 /");
  const nextPageTitle = await page.locator(".detail h3").first().textContent();
  await page.keyboard.press("ArrowLeft");
  await expect(page.locator(".detail h3").first()).toHaveText(lastOnPage);
  await page.keyboard.press("Escape");
  await page.locator("#next").click();
  await expect(titles.first()).toHaveText(nextPageTitle);
  await page.locator("#search").fill("Forrest Gump");
  await expect(titles).toHaveCount(1);
  await titles.first().click();
  await expect(page.locator("#film-next")).toHaveCount(0);
  await expect(page.locator("#film-previous")).toHaveCount(0);
  await page.locator("#modal-close").click();
});
