import { test, expect } from "@playwright/test";

test("film navigation follows results across pages and closes only on outside clicks", async ({ page }) => {
  await page.goto("/");
  await expect(page.locator("#table-view tbody tr")).toHaveCount(50, { timeout: 15000 });
  const titles = page.locator("#table-view .title-button");
  const first = await titles.first().textContent();
  const second = await titles.nth(1).textContent();
  const lastOnPage = await titles.nth(49).textContent();
  await titles.first().click();
  await expect(page.locator("#film-previous")).toBeDisabled();
  await page.locator("#film-next").click();
  await expect(page.locator(".detail h3").first()).toHaveText(second);
  await page.locator(".detail h3").first().click();
  await expect(page.locator("#modal")).toBeVisible();
  await page.keyboard.press("ArrowLeft");
  await expect(page.locator(".detail h3").first()).toHaveText(first);
  await page.mouse.click(2, 2);
  await expect(page.locator("#modal")).not.toBeVisible();
  await titles.nth(49).click();
  await page.locator("#film-next").click();
  await expect(page.locator(".film-navigation [role=status]")).toContainText("51 /");
  const nextPageTitle = await page.locator(".detail h3").first().textContent();
  await page.keyboard.press("ArrowLeft");
  await expect(page.locator(".detail h3").first()).toHaveText(lastOnPage);
  await page.keyboard.press("Escape");
  await page.locator("#next").click();
  await expect(titles.first()).toHaveText(nextPageTitle);
  await page.locator("#search").fill("Forrest Gump");
  await expect(titles).toHaveCount(1);
  await titles.first().click();
  await expect(page.locator("#film-next")).toBeDisabled();
  await expect(page.locator("#film-previous")).toBeDisabled();
  await page.locator("#modal-close").click();
  await page.locator("#view-cards").click();
  await page.locator("#cards-view .title-button").click();
  await expect(page.locator(".detail h3").first()).toHaveText("Forrest Gump");
  await page.mouse.click(2, 2);
  await expect(page.locator("#modal")).not.toBeVisible();
});
